name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main   # Roda sempre que fizer push na branch main

permissions:
  contents: write   # Dá permissão para escrever na branch gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      # Caso queira rodar build/minificação, coloque aqui.
      # Para projeto estático simples, basta publicar.

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # Certifique-se que index.html está na raiz do repo
