name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout código
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalar dependências para lint e minificação
      - name: Instalar dependências
        run: |
          npm install -g htmlhint stylelint eslint clean-css-cli

      # 4. Rodar lint no HTML
      - name: Lint HTML
        run: |
          htmlhint "**/*.html" || true

      # 5. Rodar lint no CSS
      - name: Lint CSS
        run: |
          stylelint "**/*.css" || true

      # 6. Rodar lint no JS
      - name: Lint JS
        run: |
          eslint "**/*.js" || true

      # 7. Deploy para GitHub Pages
      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      # 8. Notificação no log
      - name: Finalizar Deploy
        run: |
          echo "✅ Deploy concluído com sucesso em: https://$GITHUB_REPOSITORY_OWNER.github.io/$(basename $GITHUB_REPOSITORY)"
