name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main   # Roda sempre que fizer push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      # Não tem build, mas se quisesse rodar um minificador/otimizador poderia colocar aqui
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .   # Raiz do projeto (onde está o index.html)